# Generated by Django 4.2.1 on 2023-07-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MecanicaAutomotora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.ForeignKey(default='Nueva Categoria', on_delete=django.db.models.deletion.CASCADE, to='MecanicaAutomotora.categoria'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(default='fotos/noImg.jpg', null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='mecanico',
            field=models.ForeignKey(default='Nuevo Mecanico', on_delete=django.db.models.deletion.CASCADE, to='MecanicaAutomotora.mecanico'),
        ),
    ]
